# Generated by Django 3.1.3 on 2020-11-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201111_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='color',
        ),
    ]
