# Generated by Django 3.1.3 on 2020-12-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201211_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealofday',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='dealofday',
            name='sale_price',
        ),
    ]
