# Generated by Django 3.1.3 on 2021-05-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderstatusupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Shipping Pending'), ('2', 'Shipped'), ('4', 'Cancelled'), ('3', 'Delivered')], default='1', max_length=2),
        ),
    ]
