# Generated by Django 3.1.3 on 2021-05-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210508_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='categories/default.png', max_length=255, null=True, upload_to='categories', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, help_text='These are products that are recommended to accompany themain product.', through='shop.ProductRecommendation', to='shop.Product', verbose_name='Recommended products'),
        ),
    ]
