# Generated by Django 3.1.3 on 2021-05-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210510_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, default='categories/default.png', max_length=255, null=True, upload_to='categories', verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='categories             default.png', max_length=255, null=True, upload_to='categories', verbose_name='Image'),
        ),
    ]
