# Generated by Django 3.1.3 on 2021-05-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210510_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/categories', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='original',
            field=models.ImageField(max_length=255, upload_to='media/product', verbose_name='Original'),
        ),
    ]
