# Generated by Django 3.1.3 on 2021-05-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210510_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
